packages:
  - core
  - demos/*
  - docs

catalog:
  better-sqlite3: 12.2.0
  nuxt: 4.2.1
  '@nuxt/eslint': 1.10.0
  typescript: 5.9.3
  vue: 3.5.25
  vue-router: 4.6.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - puppeteer
  - sharp
  - unrs-resolver
  - vue-demi

overrides:
  vite: npm:vite@8.0.0-beta.0
  '@nuxt/vite-builder': npm:@nuxt/vite-builder-nightly@4.2.2-29390287.ffa14fe8

trustPolicy: no-downgrade
