packages:
  - core
  - demos/*
  - docs

catalog:
  better-sqlite3: 12.2.0
  nuxt: 4.3.1
  '@nuxt/eslint': 1.14.0
  typescript: 5.9.3
  vue: 3.5.27
  vue-router: 5.0.2

minimumReleaseAge: 10080

minimumReleaseAgeExclude: null

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - puppeteer
  - sharp
  - unrs-resolver
  - vue-demi

overrides:
  vite: npm:vite@8.0.0-beta.13

trustPolicy: no-downgrade

verifyDepsBeforeRun: error
