// Auto-generated by @nuxt-ignis/content
// Extend the default {} object to customize the defaults
// You can use the `defineContentCollection` helper to define more collections

import { loadContentConfig } from '@nuxt-ignis/content/config'

export default loadContentConfig({
  // your custom config here
})
