// Auto-generated by @nuxt-ignis/forms
// Extend the default {} object to customize the defaults

import { loadFormkitConfig } from '@nuxt-ignis/forms/formkit-config'

const config = loadFormkitConfig({
  // your custom config here
})

// required for Formkit
export default config
