// Auto-generated by @nuxt-ignis/forms
// Extend the default {} object to customize the defaults

import { loadVueformConfig } from '@nuxt-ignis/forms/vueform-config'

export default loadVueformConfig({
  // your custom config here
})
