import { existsSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { PublicRuntimeConfig, RuntimeConfig } from 'nuxt/schema'
import type { IgnisFormsOptions, NuxtIgnisFormsOptions } from './module'

export function ignisModuleDependencies(nuxtOptions: NuxtIgnisFormsOptions) {
  console.debug('@nuxt-ignis/forms - module dependencies are being resolved')

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const modules: Record<string, any> = {}

  const options = nuxtOptions.ignis?.forms
  const rootDir = nuxtOptions.rootDir

  if (options?.vueform?.enabled === true) {
    const userConfig = existsSync(join(rootDir, 'vueform.config.ts'))
      || existsSync(join(rootDir, 'vueform.config.js'))
    if (!userConfig) {
      // auto-generate default configuration file if not exists
      writeFileSync(join(rootDir, 'vueform.config.ts'), [
        '// Auto-generated by @nuxt-ignis/forms',
        '// Extend the default {} object to customize the defaults',
        '',
        `import { loadVueformConfig } from '@nuxt-ignis/forms/vueform-config'`,
        '',
        'export default loadVueformConfig({',
        '  // your custom config here',
        '})',
        '',
      ].join('\n'))
      console.debug('@nuxt-ignis/forms - generated vueform.config.ts in project root')
    }
    modules['@vueform/nuxt'] = {}
    console.debug('@vueform/nuxt module installed')
  }

  if (options?.formkit?.enabled === true) {
    const hasUserConfig = options.formkit?.config
      || existsSync(join(rootDir, 'formkit.config.ts'))
    if (!hasUserConfig) {
      // auto-generate default configuration file if not exists
      writeFileSync(join(rootDir, 'formkit.config.ts'), [
        '// Auto-generated by @nuxt-ignis/forms',
        '// Extend the default {} object to customize the defaults',
        '',
        `import { loadFormkitConfig } from '@nuxt-ignis/forms/formkit-config'`,
        '',
        'const config = loadFormkitConfig({',
        '  // your custom config here',
        '})',
        '',
        '// required for Formkit',
        'export default config',
        '',
      ].join('\n'))
      console.debug('@nuxt-ignis/forms - generated formkit.config.ts in project root')
    }
    modules['@formkit/nuxt'] = {
      defaults: {
        autoImport: true,
        default: options.formkit?.default || 'en',
        configFile: options.formkit?.config || './formkit.config.ts',
      },
    }
    console.debug('@formkit/nuxt module installed')
  }

  return modules
}

export function ignisModuleSetup(nuxtOptions: NuxtIgnisFormsOptions) {
  console.debug('@nuxt-ignis/forms - module setup function runs')

  const options = nuxtOptions.ignis?.forms

  // inject runtime config values
  nuxtOptions.runtimeConfig ||= {
    public: {} as PublicRuntimeConfig,
  } as RuntimeConfig

  const runtimeConfig = nuxtOptions.runtimeConfig.public as { ignis?: { forms?: IgnisFormsOptions } }
  runtimeConfig.ignis ??= {}
  runtimeConfig.ignis.forms ??= {}
  runtimeConfig.ignis.forms.formkit ??= {}
  runtimeConfig.ignis.forms.formkit.enabled ??= options?.formkit?.enabled ?? false
  runtimeConfig.ignis.forms.formkit.default ??= options?.formkit?.default ?? 'en'
  runtimeConfig.ignis.forms.formkit.config ??= options?.formkit?.config ?? './formkit.config.ts'
  runtimeConfig.ignis.forms.vueform ??= {}
  runtimeConfig.ignis.forms.vueform.enabled ??= options?.vueform?.enabled ?? false
}
