import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { addTemplate } from '@nuxt/kit'
import type { PublicRuntimeConfig, RuntimeConfig } from 'nuxt/schema'
import type { IgnisFormsOptions, NuxtIgnisFormsOptions } from './module'

export function ignisModuleDependencies(nuxtOptions: NuxtIgnisFormsOptions) {
  console.debug('@nuxt-ignis/forms - module dependencies are being resolved')

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const modules: Record<string, any> = {}

  const options = nuxtOptions.ignis?.forms
  const buildDir = nuxtOptions.buildDir

  const rootDir = nuxtOptions.rootDir

  if (options?.vueform?.enabled === true) {
    const userConfig = existsSync(join(rootDir, 'vueform.config.ts'))
      || existsSync(join(rootDir, 'vueform.config.js'))
    if (!userConfig) {
      // @vueform/nuxt checks existsSync during its setup (which runs before ours),
      // so the file must exist before the dependency's setup runs.
      // We write it here since addTemplate would be too late.
      const configPath = join(buildDir, 'vueform.config.ts')
      mkdirSync(buildDir, { recursive: true })
      writeFileSync(configPath, [
        '// Auto-generated by @nuxt-ignis/forms',
        '// Create `vueform.config.ts` in your project root to customize the defaults',
        `import { loadVueformConfig } from '#ignis-forms/vueform-config'`,
        '',
        'export default loadVueformConfig({})',
        '',
      ].join('\n'))
      modules['@vueform/nuxt'] = { defaults: { configPath } }
    }
    else {
      modules['@vueform/nuxt'] = {}
    }
    console.debug('@vueform/nuxt module installed')
  }

  if (options?.formkit?.enabled === true) {
    const hasUserConfig = options.formkit?.config
      || existsSync(join(rootDir, 'formkit.config.ts'))
    modules['@formkit/nuxt'] = {
      defaults: {
        autoImport: true,
        default: options.formkit?.default || 'en',
        configFile: options.formkit?.config || (hasUserConfig ? './formkit.config.ts' : join(buildDir, 'formkit.config.ts')),
      },
    }
    console.debug('@formkit/nuxt module installed')
  }

  return modules
}

export function ignisModuleSetup(nuxtOptions: NuxtIgnisFormsOptions, runtimeDir: string) {
  console.debug('@nuxt-ignis/forms - module setup function runs')

  const options = nuxtOptions.ignis?.forms

  // inject runtime config values
  nuxtOptions.runtimeConfig ||= {
    public: {} as PublicRuntimeConfig,
  } as RuntimeConfig

  const runtimeConfig = nuxtOptions.runtimeConfig.public as { ignis?: { forms?: IgnisFormsOptions } }
  runtimeConfig.ignis ??= {}
  runtimeConfig.ignis.forms ??= {}
  runtimeConfig.ignis.forms.formkit ??= {}
  runtimeConfig.ignis.forms.formkit.enabled ??= options?.formkit?.enabled ?? false
  runtimeConfig.ignis.forms.formkit.default ??= options?.formkit?.default ?? 'en'
  runtimeConfig.ignis.forms.formkit.config ??= options?.formkit?.config ?? './formkit.config.ts'
  runtimeConfig.ignis.forms.vueform ??= {}
  runtimeConfig.ignis.forms.vueform.enabled ??= options?.vueform?.enabled ?? false

  // register aliases so users can import load functions in their custom config files
  nuxtOptions.alias ??= {}
  nuxtOptions.alias['#ignis-forms/formkit-config'] = join(runtimeDir, 'formkit-config')
  nuxtOptions.alias['#ignis-forms/vueform-config'] = join(runtimeDir, 'vueform-config')

  const rootDir = nuxtOptions.rootDir

  // generate config files into .nuxt/ via addTemplate — only when no user config exists
  if (options?.formkit?.enabled === true
    && !options?.formkit?.config
    && !existsSync(join(rootDir, 'formkit.config.ts'))) {
    addTemplate({
      filename: 'formkit.config.ts',
      write: true,
      getContents: () => [
        '// Auto-generated by @nuxt-ignis/forms',
        '// Create `formkit.config.ts` in your project root to customize the defaults',
        `import { loadFormkitConfig } from '#ignis-forms/formkit-config'`,
        '',
        'const config = loadFormkitConfig({})',
        '',
        'export default config',
        '',
      ].join('\n'),
    })
    console.debug('@nuxt-ignis/forms - generated formkit.config.ts template')
  }

  // Note: vueform config is generated in moduleDependencies (not here)
  // because @vueform/nuxt checks existsSync during its setup which runs
  // before this module's setup. See ignisModuleDependencies.
}
