import { existsSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { addTemplate } from '@nuxt/kit'
import type { IgnisContentOptions, NuxtIgnisContentOptions } from './module'
import type { Nuxt, PublicRuntimeConfig, RuntimeConfig } from 'nuxt/schema'

// type augment for 'i18n:registerModule' hook
type I18nRegisterFn = (cfg: {
  langDir: string
  locales: Array<{ code: string, language: string, file: string }>
}) => void

declare module '@nuxt/schema' {
  interface NuxtHooks {
    'i18n:registerModule': (register: I18nRegisterFn) => void
  }
}

export function ignisModuleDependencies(nuxtOptions: NuxtIgnisContentOptions) {
  console.debug('@nuxt-ignis/content - module dependencies are being resolved')

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const modules: Record<string, any> = {}

  const options = nuxtOptions.ignis?.content

  // I18N
  if (options?.i18n?.enabled) {
    // evaluate passed in default locale
    let ignisDefaultLocale = options.i18n?.default || 'en'

    // scan locale files now so @nuxtjs/i18n has them when it initializes
    const localesDir = join(nuxtOptions.rootDir, 'i18n', 'locales')
    let localeFiles: string[] = []
    try {
      localeFiles = readdirSync(localesDir).filter(f => f.endsWith('.json'))
    } catch {
      console.warn(`No i18n locale files found in ${localesDir}`)
    }
    const localeCodes = localeFiles.map(f => f.replace('.json', ''))

    // ensure default locale exists and warn about misconfiguration
    if (localeCodes.length > 0 && !localeCodes.includes(ignisDefaultLocale)) {
      console.warn(`Configured default locale "${ignisDefaultLocale}" not found in ${localesDir}.`)
      console.warn(`Falling back to available "${localeCodes[0]}"`)
      ignisDefaultLocale = localeCodes[0]!
    }

    // pass config via `defaults` — moduleDependencies merges this into nuxt.options.i18n
    modules['@nuxtjs/i18n'] = {
      defaults: {
        locales: localeCodes.map(code => ({ code: code, file: `${code}.json` })),
        defaultLocale: ignisDefaultLocale,
      },
    }
    console.debug(`@nuxtjs/i18n module installed with locales: ${localeCodes.join(', ') || 'none'}`)
  }

  // SEO
  // module must be installed before @nuxt/content
  // (https://nuxtseo.com/docs/nuxt-seo/guides/nuxt-content)
  if (options?.seo?.enabled === true) {
    const seoConfig: Record<string, unknown> = {}

    // ogImage and Schema.org modules should be disabled with `ssr: false`
    if (nuxtOptions.ignis?.config?.nuxt?.ssr === false) {
      seoConfig.ogImage = { enabled: false }
      seoConfig.schemaOrg = { enabled: false }
    }

    // enable zero-runtime sitemap generation for static sites
    if (options.seo?.staticsite === true) {
      seoConfig.sitemap = { zeroRuntime: true }
    }

    modules['@nuxtjs/seo'] = {
      defaults: seoConfig,
    }

    console.debug('@nuxtjs/seo module installed')
  }

  // Nuxt Content
  if (options?.content?.enabled === true) {
    modules['@nuxt/content'] = {
      defaults: {
        experimental: {
          sqliteConnector: 'native',
        },
      },
    }
    console.debug('@nuxt/content module installed')

    // auto-generate default configuration file if not exists
    const rootDir = nuxtOptions.rootDir
    const userConfig = existsSync(join(rootDir, 'content.config.ts'))
    if (!userConfig) {
      writeFileSync(
        join(rootDir, 'content.config.ts'),
        [
          '// Auto-generated by @nuxt-ignis/content',
          '// Extend the default {} object to customize the defaults',
          '// You can use the `defineContentCollection` helper to define more collections',
          '',
          `import { loadContentConfig } from '@nuxt-ignis/content/config'`,
          '',
          'export default loadContentConfig({',
          '  // your custom config here',
          '})',
          '',
        ].join('\n'),
      )
      console.debug('@nuxt-ignis/content - generated content.config.ts in project root')
    }
  }

  // Social Share
  if (options?.social?.enabled === true) {
    modules['@stefanobartoletti/nuxt-social-share'] = {
      defaults: {
        baseUrl: options.social?.url || '',
      },
    }
    console.debug('@stefanobartoletti/nuxt-social-share module installed')
  }

  return modules
}

export function ignisModuleSetup(nuxtOptions: NuxtIgnisContentOptions, nuxt: Nuxt) {
  console.debug('@nuxt-ignis/content - module setup function runs')

  const options = nuxtOptions.ignis?.content

  // inject runtime config values
  nuxtOptions.runtimeConfig ||= {
    public: {} as PublicRuntimeConfig,
  } as RuntimeConfig

  const runtimeConfig = nuxtOptions.runtimeConfig.public as { ignis?: { content?: IgnisContentOptions } }
  runtimeConfig.ignis ??= {}
  runtimeConfig.ignis.content ??= {}
  runtimeConfig.ignis.content.content ??= {}
  runtimeConfig.ignis.content.content.enabled ??= options?.content?.enabled ?? false
  runtimeConfig.ignis.content.i18n ??= {}
  runtimeConfig.ignis.content.i18n.enabled ??= options?.i18n?.enabled ?? false
  runtimeConfig.ignis.content.i18n.default ??= options?.i18n?.default ?? 'en'
  runtimeConfig.ignis.content.seo ??= {}
  runtimeConfig.ignis.content.seo.enabled ??= options?.seo?.enabled ?? false
  runtimeConfig.ignis.content.seo.staticsite ??= options?.seo?.staticsite ?? false
  runtimeConfig.ignis.content.social ??= {}
  runtimeConfig.ignis.content.social.enabled ??= options?.social?.enabled ?? false
  runtimeConfig.ignis.content.social.url ??= options?.social?.url ?? ''
  runtimeConfig.ignis.content.pslo ??= {}
  runtimeConfig.ignis.content.pslo.enabled ??= options?.pslo?.enabled ?? false
  runtimeConfig.ignis.content.pslo.content ??= options?.pslo?.content ?? false

  // additional processing
  const effectiveOptions = runtimeConfig.ignis.content

  // i18n
  if (effectiveOptions.i18n?.enabled === true) {
    // scan user's i18n/locales/*.json at build time and generate static imports
    const localesDir = join(nuxtOptions.rootDir, 'i18n', 'locales')
    let localeFiles: string[] = []
    try {
      localeFiles = readdirSync(localesDir).filter(f => f.endsWith('.json'))
    } catch {
      console.warn(`No i18n locale files found in ${localesDir}`)
    }

    const localeCodes = localeFiles.map(f => f.replace('.json', ''))

    // generate a build-time template with JSON imports
    // uses relative paths from .nuxt/ for cross-platform compatibility
    const buildDir = nuxtOptions.buildDir
    const template = addTemplate({
      filename: 'ignis-i18n-locales.mjs',
      write: true,
      getContents: () => {
        const imports = localeFiles.map((file) => {
          const code = file.replace('.json', '')
          const absPath = join(localesDir, file)
          let relPath = relative(buildDir, absPath).replace(/\\/g, '/')
          if (!relPath.startsWith('.')) {
            relPath = './' + relPath
          }
          return `import ${code} from '${relPath}' with { type: 'json' }`
        })
        return [
          '// Auto-generated by @nuxt-ignis/content',
          ...imports,
          '',
          `export const localeMessages = { ${localeCodes.join(', ')} }`,
          `export const localeNames = [${localeCodes.map(c => `{ code: '${c}', file: '${c}.json' }`).join(', ')}]`,
          '',
        ].join('\n')
      },
    })

    // register alias for both Nuxt app and Nitro server
    nuxtOptions.alias ??= {}
    nuxtOptions.alias['#ignis-i18n-locales'] = template.dst
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const nitro = ((nuxtOptions as any).nitro ??= {})
    nitro.alias ??= {}
    nitro.alias['#ignis-i18n-locales'] = template.dst

    // register discovered locales with @nuxtjs/i18n via its dedicated hook
    // see: https://i18n.nuxtjs.org/docs/guide/extend-messages
    if (nuxt && localeCodes.length > 0) {
      nuxt.hook('i18n:registerModule', (register) => {
        register({
          langDir: localesDir,
          locales: localeCodes.map(code => ({
            code,
            language: code,
            file: `${code}.json`,
          })),
        })
      })
    }

    console.debug(`i18n enabled with default locale: ${effectiveOptions.i18n?.default}`)
    console.debug(`i18n locale files found: ${localeCodes.join(', ') || 'none'}`)
  }

  // elrh-pslo
  if (effectiveOptions.pslo?.enabled === true) {
    console.debug('elrh-pslo enabled')
  }

  if (effectiveOptions.social?.enabled === true) {
    // @ts-expect-error 'socialShare' option will exist at this point
    if (!nuxtOptions.socialShare?.baseUrl && !effectiveOptions.social?.url) {
      console.warn('Base URL for `nuxt-social-share` is not set. Check https://nuxt-ignis.com/3-7-features-utils.html#nuxt-social-share to set it up correctly.')
    }
  }
}
